services:
  app:
    build:
      context: ./docker/development/php
      dockerfile: Dockerfile
      args:
        - user=${USER}
        - uid=${UID}
    image: json2html-dev
    stdin_open: true
    tty: true
    container_name: json2html-app
    working_dir: /var/www/html
    ports:
      - "8000-8010:8000"
    volumes:
      - ${PWD}/:/var/www/html